name = "tabula-rasa"
description = "A nice template to see how things work and to add new functionalities."
license = "MIT"
licenselink = "https://github.com/otaviokr/tabula-rasa/LICENSE"
homepage = "https://github.com/otaviokr/tabula-rasa"
tags = ["blog", "personal", "minimalist"]
features = ["sidebar", "bootstrap3"]

[author]
  name = "Otavio K Rofatto"
  homepage = "http://otaviokr.github.io"

paginate = 1O